import React,{useState} from 'react';
import { useNavigate } from 'react-router-dom';
import "../App.css";
import Toast from '../Toast/ToastMess';
const features = [
  { title: 'AI Doubt Solver', desc: 'Ask doubts via text or image. Our AI instantly solves them with explanations.', link: '/ai-doubt-solver' },
  { title: 'Test Series', desc: 'Practice full-length JEE mock tests and get your ranking in real-time.', link: '/test-series' },
  { title: 'Study Materials', desc: 'Access top-quality notes, video lectures, and PDFs curated by experts.', link: '/study-materials' },
  { title: 'Progress Dashboard', desc: 'Track your weekly performance, test scores, and suggested improvements.', link: '/progress-dashboard' },
  { title: 'Smart Scheduler', desc: 'Get a personalized study plan auto-adjusted based on your syllabus & time.', link: '/smart-scheduler' },
  { title: 'Flashcards & Revisions', desc: 'Revise key concepts with spaced-repetition flashcards generated by AI.', link: '/flashcards-revisions' },
  { title: 'Mentorship', desc: 'Connect with top mentors for guidance and personalized study tracking.', link: '/mentorship' },
  { title: 'Discussion Forums', desc: 'Ask and answer questions. Engage with other aspirants in structured threads.', link: '/discussion-forums' },
];

const Features = () => {
   const [toastMsg,setToastMsg]=useState(null);
  const navigate = useNavigate();

  const handleClick = (link) => {
    const user =localStorage.getItem("user");
    if (user) {
      navigate(link);
    } else {
     setToastMsg("Login to Continue");
    }
  };

  return (

    <section className="features" id="features">
      {toastMsg && (
        <Toast message={toastMsg} onClose={() => setToastMsg(null)} />
      )}
      {features.map((f, i) => (
        <div className="card" key={i} onClick={() => handleClick(f.link)} style={{ cursor: 'pointer' }}>
          <h3>{f.title}</h3>
          <p>{f.desc}</p>
        </div>
      ))}
    </section>
  );
};

export default Features;
